### ISSUE TITLE
Normal task

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/comdor#120]
Normal task which should have the default DEV role and 60min estimation...

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@amihaiemil I couldn't find any assignee for this task. This is either because there are no contributors with role ``DEV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.
