### ISSUE TITLE
QA Task With Wrong Assingee

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/comdor#124]
Initial assignee doesn't have QA role

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. Unfortunately, @amihaiemil is not a contributor with the required role (QA), that's why I unassigned them. 

I will assign a contributor to take care of it soon.

**Comment by charlesmike** [comment]
@amihaiemil I couldn't find any assignee for this task. This is either because there are no contributors with role ``QA`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.
