### ISSUE TITLE
Website for it

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/comdor#6]
It needs a website. Start it on branch ``gh-pages``.

**Comment by amihaiemil** [comment]
@charlesmike try to index this pls

**Comment by charlesmike** [comment]
> @charlesmike try to index this pls

@amihaiemil sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike try to index this site pls

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/205d594c-f28d-4451-be27-b8d4363a617a.log).

**Comment by charlesmike** [comment]
> @charlesmike try to index this site pls

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See the [logs](http://charles.amihaiemil.com/logs.html?log=/205d594c-f28d-4451-be27-b8d4363a617a.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)
